export const GET_CAPSULE_LOADING = 'GET_CAPSULE_LOADING'
export const GET_CAPSULE_SUCCESS = 'GET_CAPSUEL_SUCCESS'
export const GET_CAPSULE_FAILED = 'GET_CAPSULE_FAILED'


export const INCREMENT_PAGE_NO = 'INCREMENT_PAGE_NO'

export const FILTER_CAPSULE = 'FILTER_CAPSULE'